-- Удаление дублирующих индексов.
-- Каждый из них полностью перекрыт другим индексом той же таблицы
-- (совпадает либо является его левым префиксом), поэтому на чтение
-- не влияет, но замедляет каждую вставку и занимает место.
-- Сформировано 2026-08-11.

-- analysis_data.idx_analysis_data_entity (legal_entity) перекрыт uq_entity_sku (legal_entity,sku)
ALTER TABLE `analysis_data` DROP INDEX `idx_analysis_data_entity`;
-- analysis_data.idx_analysis_data_legal_entity (legal_entity) перекрыт idx_analysis_data_entity (legal_entity)
ALTER TABLE `analysis_data` DROP INDEX `idx_analysis_data_legal_entity`;
-- audit_log.idx_audit_log_entity (entity_type,entity_id) перекрыт idx_audit_log_entity_created (entity_type,entity_id,created_at)
ALTER TABLE `audit_log` DROP INDEX `idx_audit_log_entity`;
-- cabinet_external_link_visibility.idx_link (link_id) перекрыт uq_link_scope (link_id,scope_type,scope_value)
ALTER TABLE `cabinet_external_link_visibility` DROP INDEX `idx_link`;
-- deficit_restaurant_stock.idx_token (token_id) перекрыт uniq_token_rest (token_id,restaurant_number)
ALTER TABLE `deficit_restaurant_stock` DROP INDEX `idx_token`;
-- deficit_tokens.idx_token (token) перекрыт token (token)
ALTER TABLE `deficit_tokens` DROP INDEX `idx_token`;
-- delivery_schedule.idx_delivery_schedule_restaurant_id (restaurant_id) перекрыт uq_rest_day (restaurant_id,day_of_week)
ALTER TABLE `delivery_schedule` DROP INDEX `idx_delivery_schedule_restaurant_id`;
-- dist_entries.idx_session_product (session_product_id) перекрыт uniq_sp_rest (session_product_id,restaurant_number)
ALTER TABLE `dist_entries` DROP INDEX `idx_session_product`;
-- keg_returns.idx_keg_restaurant (restaurant_id) перекрыт uq_keg_bso (restaurant_id,bso_series,bso_number)
ALTER TABLE `keg_returns` DROP INDEX `idx_keg_restaurant`;
-- keg_return_items.idx_kri_request (request_id) перекрыт uq_kri (request_id,keg_code)
ALTER TABLE `keg_return_items` DROP INDEX `idx_kri_request`;
-- notifications.idx_notifications_type_date (type,created_at) перекрыт idx_notifications_type_created_at (type,created_at)
ALTER TABLE `notifications` DROP INDEX `idx_notifications_type_date`;
-- op_production_schedule.idx_op_sched_supplier (supplier_id) перекрыт uniq_op_sched (supplier_id,delivery_dow,batch_no)
ALTER TABLE `op_production_schedule` DROP INDEX `idx_op_sched_supplier`;
-- order_items.idx_order_items_order_id (order_id) перекрыт uk_order_items_order_sku (order_id,sku)
ALTER TABLE `order_items` DROP INDEX `idx_order_items_order_id`;
-- pallet_reference.idx_pallet_reference_le_group (legal_entity_group) перекрыт uk_pallet_ref_group_name (legal_entity_group,name)
ALTER TABLE `pallet_reference` DROP INDEX `idx_pallet_reference_le_group`;
-- price_history.idx_ph_date (changed_at) перекрыт idx_price_history_changed (changed_at,legal_entity)
ALTER TABLE `price_history` DROP INDEX `idx_ph_date`;
-- products.idx_products_le_group (legal_entity_group) перекрыт idx_products_group_active_sku (legal_entity_group,is_active,sku)
ALTER TABLE `products` DROP INDEX `idx_products_le_group`;
-- product_barcodes.idx_pb_barcode (barcode) перекрыт uk_pb_barcode_sku (barcode,sku)
ALTER TABLE `product_barcodes` DROP INDEX `idx_pb_barcode`;
-- protocol_decision_cards.idx_pdc_decision (decision_id) перекрыт PRIMARY (decision_id,card_id)
ALTER TABLE `protocol_decision_cards` DROP INDEX `idx_pdc_decision`;
-- reminder_acknowledgements.idx_ra_restaurant (restaurant_id) перекрыт uniq_ack (restaurant_id,reminder_kind,supplier_id,target_date,order_day)
ALTER TABLE `reminder_acknowledgements` DROP INDEX `idx_ra_restaurant`;
-- reminder_runs.idx_rr_subscription (subscription_id) перекрыт uniq_run (subscription_id,reminder_kind,target_date,order_day,run_hour,channel,recipient)
ALTER TABLE `reminder_runs` DROP INDEX `idx_rr_subscription`;
-- restaurant_keg_return_tg_subscribers.idx_rkrts_sub (subscription_id) перекрыт uniq_rkrts_pair (subscription_id,ro_tg_sub_id)
ALTER TABLE `restaurant_keg_return_tg_subscribers` DROP INDEX `idx_rkrts_sub`;
-- restaurant_main_delivery_tg_subscribers.idx_rmdts_sub (subscription_id) перекрыт uniq_rmdts_pair (subscription_id,ro_tg_sub_id)
ALTER TABLE `restaurant_main_delivery_tg_subscribers` DROP INDEX `idx_rmdts_sub`;
-- restaurant_reminder_subscriptions.idx_rrs_restaurant (restaurant_id) перекрыт uniq_rrs_pair (restaurant_id,supplier_id)
ALTER TABLE `restaurant_reminder_subscriptions` DROP INDEX `idx_rrs_restaurant`;
-- restaurant_reminder_tg_subscribers.idx_rrts_sub (subscription_id) перекрыт uniq_rrts_pair (subscription_id,ro_tg_sub_id)
ALTER TABLE `restaurant_reminder_tg_subscribers` DROP INDEX `idx_rrts_sub`;
-- restaurant_sales.idx_restaurant_sales_legal_entity (legal_entity_group) перекрыт idx_restaurant_sales_group_date_analog (legal_entity_group,sale_date,analog_group)
ALTER TABLE `restaurant_sales` DROP INDEX `idx_restaurant_sales_legal_entity`;
-- restaurant_sales.idx_rs_date (sale_date) перекрыт uk_rs_date_group_entity (sale_date,analog_group,legal_entity_group)
ALTER TABLE `restaurant_sales` DROP INDEX `idx_rs_date`;
-- ro_orders.idx_ro_orders_date (delivery_date) перекрыт idx_ro_orders_date_status (delivery_date,status)
ALTER TABLE `ro_orders` DROP INDEX `idx_ro_orders_date`;
-- ro_order_items.idx_ro_items_order (order_id) перекрыт uk_ro_items_order_sku (order_id,sku)
ALTER TABLE `ro_order_items` DROP INDEX `idx_ro_items_order`;
-- ro_telegram_subs.idx_rest_group (restaurant_number,legal_entity_group) перекрыт u_rest_group_chat (restaurant_number,legal_entity_group,chat_id)
ALTER TABLE `ro_telegram_subs` DROP INDEX `idx_rest_group`;
-- ro_tg_tokens.idx_token (token) перекрыт token (token)
ALTER TABLE `ro_tg_tokens` DROP INDEX `idx_token`;
-- so_orders.idx_so_orders_supplier (supplier_id) перекрыт idx_so_orders_supplier_date_entity_rest (supplier_id,delivery_date,legal_entity,restaurant_number)
ALTER TABLE `so_orders` DROP INDEX `idx_so_orders_supplier`;
-- so_order_items.idx_so_items_order (order_id) перекрыт uk_so_items_order_sku_batch (order_id,sku,batch_no)
ALTER TABLE `so_order_items` DROP INDEX `idx_so_items_order`;
-- so_reminder_mutes.idx_supplier (supplier_id) перекрыт PRIMARY (supplier_id,restaurant_id)
ALTER TABLE `so_reminder_mutes` DROP INDEX `idx_supplier`;
-- so_supplier_temp_schedule_items.idx_so_temp_schedule_period (period_id) перекрыт uq_so_temp_schedule_item (period_id,restaurant_id,delivery_day)
ALTER TABLE `so_supplier_temp_schedule_items` DROP INDEX `idx_so_temp_schedule_period`;
-- so_template_visibility.idx_template (template_id) перекрыт uniq_tpl_kind_scope (template_id,kind,scope_type,scope_value)
ALTER TABLE `so_template_visibility` DROP INDEX `idx_template`;
-- stock_collection_data.idx_collection (collection_id) перекрыт idx_collection_product_rest_expiry (collection_id,product_id,restaurant_number,expiry_date)
ALTER TABLE `stock_collection_data` DROP INDEX `idx_collection`;
-- stock_collection_drafts.idx_sc_draft_coll (collection_id) перекрыт uniq_sc_draft (collection_id,restaurant_number)
ALTER TABLE `stock_collection_drafts` DROP INDEX `idx_sc_draft_coll`;
-- stock_collection_mail_log.idx_collection (collection_id) перекрыт uniq_coll_rest_kind (collection_id,restaurant_number,kind)
ALTER TABLE `stock_collection_mail_log` DROP INDEX `idx_collection`;
-- stock_malling.idx_expiry_date (expiry_date) перекрыт idx_stock_malling_expiry (expiry_date,expiry_status,customer)
ALTER TABLE `stock_malling` DROP INDEX `idx_expiry_date`;
-- suppliers.idx_suppliers_le_group (legal_entity_group) перекрыт idx_suppliers_group_active_name (legal_entity_group,is_active,short_name)
ALTER TABLE `suppliers` DROP INDEX `idx_suppliers_le_group`;
-- supplier_schedules.idx_ss_supplier (supplier_id) перекрыт uq_ss_schedule_delivery (supplier_id,restaurant_id,delivery_day)
ALTER TABLE `supplier_schedules` DROP INDEX `idx_ss_supplier`;
-- supplier_schedule_deadlines.idx_sd_supplier (supplier_id) перекрыт uniq_sd_pair_day (supplier_id,restaurant_id,order_day)
ALTER TABLE `supplier_schedule_deadlines` DROP INDEX `idx_sd_supplier`;
-- survey_response_files.idx_srf_response (response_id) перекрыт idx_srf_cleanup (response_id,created_at)
ALTER TABLE `survey_response_files` DROP INDEX `idx_srf_response`;
-- tasks_assignees.idx_ta_user (user_name) перекрыт idx_ta_user_done (user_name,is_done)
ALTER TABLE `tasks_assignees` DROP INDEX `idx_ta_user`;
-- tasks_card_dependencies.idx_tcd_blocker (blocker_card_id) перекрыт uk_tcd_pair (blocker_card_id,blocked_card_id)
ALTER TABLE `tasks_card_dependencies` DROP INDEX `idx_tcd_blocker`;
-- tg_notification_log.idx_tg_notif_log (notification_type,legal_entity,chat_id,sent_at) перекрыт idx_lookup (notification_type,legal_entity,chat_id,sent_at)
ALTER TABLE `tg_notification_log` DROP INDEX `idx_tg_notif_log`;
-- tl_assignments.idx_tl_assign_truck (truck_id) перекрыт idx_tl_assignments_truck_sort (truck_id,sort_order,id)
ALTER TABLE `tl_assignments` DROP INDEX `idx_tl_assign_truck`;
-- user_sessions.idx_token (token) перекрыт token (token)
ALTER TABLE `user_sessions` DROP INDEX `idx_token`;
-- user_sessions.idx_user_sessions_expires (expires_at) перекрыт idx_expires (expires_at)
ALTER TABLE `user_sessions` DROP INDEX `idx_user_sessions_expires`;
-- veg_orders.idx_session (session_id) перекрыт uniq_order (session_id,product_id,restaurant_number,delivery_date)
ALTER TABLE `veg_orders` DROP INDEX `idx_session`;
-- veg_tokens.idx_token (token) перекрыт token (token)
ALTER TABLE `veg_tokens` DROP INDEX `idx_token`;
-- warehouse_cells.idx_wc_date (report_date) перекрыт uk_date_entity_type (report_date,legal_entity,stock_type)
ALTER TABLE `warehouse_cells` DROP INDEX `idx_wc_date`;
